services:
  damlok_frontend:
    build:
      context: ./damlok_frontend
      dockerfile: Dockerfile.dev

    ports:
      - "5173:5173"

    volumes:
      - ./damlok_frontend:/app
      - /app/node_modules

    env_file:
      - ./.env

    depends_on:
      - damlok_backend
      - damlok_AI

  damlok_backend:
    build:
      context: ./damlok_backend
      dockerfile: Dockerfile.dev

    ports:
      - "8080:8080"

    volumes:
      - ./damlok_frontend:/app
      - ~/.m2:/root/.m2

    env_file:
      - ./.env

    depends_on:
      - damlok_AI

  damlok_AI:
    build:
      context: ./damlok_frontend
      dockerfile: Dockerfile.dev

    ports:
      - "9000:9000"

    volumes:
      - ./damlok_frontend:/app

    env_file:
      - ./.env
